#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

menuentry "FreeBSD" {
   load_video
   set root='(hd0,gpt1)'
   #chainloader (hd0,gpt2)+1
   chainloader /efi/boot/BOOTx64.efi
}

# After add those lines above, you must run the command below (on CentOS):
# grub2-mkconfig -o /boot/efi/EFI/centos/grub.cfg
